name: Scanning for secrets in commits
on:
 pull_request:
    branches:
      - master
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 10
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@6171fa9f6676edf21e15bba41f049b18399d7372 # main
      with:
        extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
